name: 11 - using inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "skip deployment and only print build output"
        default: false
      target:
        type: environment
        required: true
        description: "which environment the workflow will target"
      tag:
        type: choice
        description: 'release from which to build and deploy'
        required: true
        options:
          - v1
          - v2
          - v3
        default: v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "building from tag ${{inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{inputs.target}}
    needs: builds
    steps:
      - name: deploy
        run: echo "deploying to ${{inputs.target}}"
